services:
  nginx:
    build:
      context: docker/nginx
    ports:
      - "80:80"
    volumes:
      - ./:/app
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: docker/php-fpm
    volumes:
      - ./:/app
    environment:
      APP_DEBUG: 1
      APP_ENV: dev

  php-cli:
    build:
      context: docker/php-cli
    volumes:
      - ./:/app

  postgres:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "54321:5432"

volumes:
  postgres:
